runaiProjects: 
  ## here you should list all the projects that you would like to get notifications from 
  - my_runai_project
  - stam_odd_project

clusterName: ""

slack:
  enabled: true
  apiToken: ""
  # set to a specific channel `runai-notifications` or 
  # a user `@bob` or
  # set 'pod-project' in order to send the notification dynamically to `@project` - configured on the pod labels 
  channel: ""


